"""FTDI MPSSE backend, built directly on pyusb.

Drives an FT232H or FT2232H in MPSSE mode to give real hardware SPI at mode 0.

Why not `pyftdi`?  Every pyftdi release on PyPI declares
``requires_python >= 3.5``, so it cannot run on Python 2.7, which this
library targets.  `pylibftdi` supports 2.7 only up to a pinned old release
and additionally needs a system ``libftdi`` shared library.  pyusb is already
a dependency of the FX2 backend and works on 2.7, so the MPSSE protocol is
spoken directly here.  See FTDI application note AN_108.

The MPSSE byte stream is generated by the two module-level functions below,
which are pure and therefore testable without any hardware attached.
"""

from __future__ import division, print_function

from .base import SerialWordBackend


# FT232H, then FT2232H.
USB_IDS = ((0x0403, 0x6014), (0x0403, 0x6010))

# FTDI vendor control requests.
SIO_RESET = 0x00
SIO_SET_LATENCY_TIMER = 0x09
SIO_SET_BITMODE = 0x0B

SIO_RESET_SIO = 0
SIO_RESET_PURGE_RX = 1
SIO_RESET_PURGE_TX = 2

BITMODE_RESET = 0x00
BITMODE_MPSSE = 0x02

# MPSSE opcodes (AN_108).
CMD_CLOCK_BYTES_OUT_NEG_MSB = 0x11    # data changes on the falling edge
CMD_SET_BITS_LOW = 0x80
CMD_SET_CLOCK_DIVISOR = 0x86
CMD_SEND_IMMEDIATE = 0x87
CMD_DISABLE_CLK_DIV5 = 0x8A
CMD_DISABLE_3PHASE_CLK = 0x8D
CMD_DISABLE_ADAPTIVE_CLK = 0x97

# ADBUS pin assignment, the conventional MPSSE SPI wiring.
PIN_SCK = 0x01                        # ADBUS0 -> ADF4351 CLK
PIN_DO = 0x02                         # ADBUS1 -> ADF4351 DATA
PIN_DI = 0x04                         # ADBUS2 (unused; ADF4351 has no MISO)
PIN_LE = 0x08                         # ADBUS3 -> ADF4351 LE
DIRECTION = PIN_SCK | PIN_DO | PIN_LE  # 0x0B: three outputs, DI is an input

#: MPSSE master clock once the divide-by-5 prescaler is disabled.
MASTER_CLOCK_HZ = 60000000

_BULK_OUT_EP = 0x02
_BULK_IN_EP = 0x81
_INTERFACE_A = 1

_VENDOR_OUT = 0x40


def clock_divisor(frequency_hz):
    """MPSSE divisor giving the highest TCK not exceeding `frequency_hz`.

    TCK = MASTER_CLOCK_HZ / ((1 + divisor) * 2)
    """
    if frequency_hz <= 0:
        raise ValueError('frequency_hz must be positive')
    divisor = int(MASTER_CLOCK_HZ // (2 * frequency_hz)) - 1
    if divisor < 0:
        divisor = 0
    if divisor > 0xFFFF:
        divisor = 0xFFFF
    return divisor


def mpsse_init_commands(frequency_hz=1000000):
    """Byte stream that puts the MPSSE engine into SPI mode 0."""
    divisor = clock_divisor(frequency_hz)
    return bytearray((
        CMD_DISABLE_CLK_DIV5,          # master clock is 60 MHz, not 12 MHz
        CMD_DISABLE_ADAPTIVE_CLK,
        CMD_DISABLE_3PHASE_CLK,        # one edge out, one edge in
        CMD_SET_CLOCK_DIVISOR, divisor & 0xFF, (divisor >> 8) & 0xFF,
        CMD_SET_BITS_LOW, 0x00, DIRECTION,   # CLK low, DATA low, LE low
    ))


def mpsse_word_commands(word):
    """Byte stream that shifts one 32-bit register word out and latches it.

    Data is clocked out MSB first on the falling edge, so the ADF4351 samples
    each bit on the following rising edge -- SPI mode 0.  LE is held low
    throughout and then pulsed high, which is the edge that transfers the
    shift register into the latch named by the three control bits.
    """
    word &= 0xFFFFFFFF
    payload = SerialWordBackend.word_to_bytes(word)
    commands = bytearray()
    commands += bytearray((CMD_SET_BITS_LOW, 0x00, DIRECTION))     # LE low
    # Length field is (number of bytes - 1), little endian.
    commands += bytearray((CMD_CLOCK_BYTES_OUT_NEG_MSB, 0x03, 0x00))
    commands += payload
    commands += bytearray((CMD_SET_BITS_LOW, PIN_LE, DIRECTION))   # LE high
    commands += bytearray((CMD_SET_BITS_LOW, 0x00, DIRECTION))     # LE low
    commands += bytearray((CMD_SEND_IMMEDIATE,))
    return commands


class FtdiBackend(SerialWordBackend):
    """ADF4351 behind an FT232H/FT2232H in MPSSE mode.  Requires `pyusb`.

    Untested against real silicon: the author had no FTDI part on the bench.
    The generated MPSSE byte stream is unit tested, but the USB plumbing is
    not.  Treat this as a starting point rather than a proven path.
    """

    def __init__(self, dev=None, frequency_hz=1000000, interface=_INTERFACE_A):
        import usb.core
        import usb.util
        self._usb_util = usb.util

        if dev is None:
            for vid, pid in USB_IDS:
                dev = usb.core.find(idVendor=vid, idProduct=pid)
                if dev is not None:
                    break
        if dev is None:
            raise ValueError(
                'no FTDI MPSSE device found (looked for %s)'
                % ', '.join('%04x:%04x' % ids for ids in USB_IDS))

        self.dev = dev
        self.interface = interface
        self.dev.set_configuration()

        self._control(SIO_RESET, SIO_RESET_SIO)
        self._control(SIO_RESET, SIO_RESET_PURGE_RX)
        self._control(SIO_RESET, SIO_RESET_PURGE_TX)
        self._control(SIO_SET_LATENCY_TIMER, 1)
        # A reset out of MPSSE and back in is what FTDI's own examples do.
        self._control(SIO_SET_BITMODE, (BITMODE_RESET << 8) | 0x00)
        self._control(SIO_SET_BITMODE, (BITMODE_MPSSE << 8) | DIRECTION)

        self._write(mpsse_init_commands(frequency_hz))

    def _control(self, request, value):
        self.dev.ctrl_transfer(
            bmRequestType=_VENDOR_OUT, bRequest=request,
            wValue=value, wIndex=self.interface, data_or_wLength=None)

    def _write(self, data):
        self.dev.write(_BULK_OUT_EP, data)

    def write_word(self, word):
        self._write(mpsse_word_commands(word))

    def close(self):
        if self.dev is not None:
            try:
                self._control(SIO_SET_BITMODE, (BITMODE_RESET << 8) | 0x00)
            finally:
                self._usb_util.dispose_resources(self.dev)
                self.dev = None
